/*Conectar Databases*/ 
SHOW DATABASES;
/*Crear base de datos*/ 
CREATE DATABASE dbelectrodomesticos;
 /*Poner en uso base de datos*/
USE dbelectrodomesticos; 
 /*Crear tabla CLIENTE*/
CREATE TABLE CLIENTE (
    CODCLI CHAR(4),
    NOMCLI VARCHAR(60),
    APECLI VARCHAR(80),
    EMACLI VARCHAR(80),
    CELCLI CHAR(9),
    DIRCLI VARCHAR(70),
    ESTCLI CHAR(1),
    PRIMARY KEY (CODCLI)
);

 /*Crear tabla VENDEDOR*/
CREATE TABLE VENDEDOR (
    CODVEND CHAR(4),
    NOMVEND VARCHAR(60),
    APEVEND VARCHAR(80),
    EMAVEND VARCHAR(80),
    CELVEND CHAR(9),
    DIRVEND VARCHAR(70),
    ESTVEND CHAR(1),
    PRIMARY KEY (CODVEND)
);

/*Crear tabla PRODUCTO*/
CREATE TABLE PRODUCTO (
    CODPRO CHAR(5),
    DESCPRO VARCHAR(80),
    CATPRO CHAR(1),
    PREPRO DECIMAL(8,2),
    STOCKPRO INTEGER,
    ESTPRO CHAR(1),
    PRIMARY KEY (CODPRO)
);

/*Crear tabla PROVEEDOR*/
CREATE TABLE PROVEEDOR (
    CODPROV CHAR(5),
    RAZSOCPROV VARCHAR(90),
    RUCPROV VARCHAR(11),
    EMAPROV VARCHAR(70),
    ESTPROV CHAR(1),
    PRIMARY KEY (CODPROV)
);

/*Crear tabla VENTA*/
CREATE TABLE VENTA (
    CODVEN CHAR(5),
    FECVEN DATETIME,
    CODCLI CHAR(4),
    CODVEND CHAR(4),
    ESTVEN CHAR(1),
    PRIMARY KEY (CODVEN)
);

/*Crear tabla VENTADETALLE*/
CREATE TABLE VENTADETALLE (
    IDVENDET INTEGER,
    CODVEN CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INTEGER,
    PRIMARY KEY (IDVENDET)
);

/*Crear tabla COMPRA*/
CREATE TABLE COMPRA(
    CODCOM CHAR(5),
    FECCOM DATETIME,
    CODVEND CHAR(4),
    CODPROV CHAR(5),
    ESTCOM CHAR(1),
    PRIMARY KEY (CODCOM)
);

/*Crear tabla COMPRADETALLE*/
CREATE TABLE COMPRADETALLE (
    IDCOMDET INTEGER,
    CODCOM CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INTEGER,
    PRIMARY KEY (IDCOMDET)
);


/*RELACIONAMOS TABLAS*/
 ALTER TABLE VENTA
 ADD
 FOREIGN KEY(CODCLI) 
 REFERENCES CLIENTE (CODCLI)
 ;

 ALTER TABLE VENTA
 ADD
 FOREIGN KEY(CODVEND) 
 REFERENCES VENDEDOR (CODVEND)
 ;

 ALTER TABLE VENTADETALLE
 ADD
 FOREIGN KEY(CODVEN) 
 REFERENCES VENTA (CODVEN)
 ;

 ALTER TABLE VENTADETALLE
 ADD
 FOREIGN KEY(CODPRO) 
 REFERENCES PRODUCTO (CODPRO)
 ;

 ALTER TABLE COMPRADETALLE
 ADD
 FOREIGN KEY(CODCOM) 
 REFERENCES COMPRA (CODCOM)
 ;

 ALTER TABLE COMPRADETALLE
 ADD
 FOREIGN KEY(CODPRO) 
 REFERENCES PRODUCTO (CODPRO)
 ;

 ALTER TABLE COMPRA
 ADD
 FOREIGN KEY(CODPROV) 
 REFERENCES PROVEEDOR (CODPROV)
 ;

 ALTER TABLE COMPRA
 ADD
 FOREIGN KEY(CODVEND) 
 REFERENCES VENDEDOR (CODVEND)
 ;
